### ISSUE TITLE
Coveo search crawler causing Null reference exception

### ISSUE THREAD

**Issue by jdearsley** [chowson/Sitecore.51Degress.CloudDeviceDetection#2]
So we have upgraded our instance to Sitecore 8.2, and one of our last sticking points is the integration of Coveo 4.0 and the CloudDeviceDetection package.

We are seeing a null reference exception when we apply a rule to our mobile device "When the visitors device is Mobile" (the device does have a fallback to default).

When an item is crawled its calling the get_Layout method within Sitecore, however its not a real HttpRequest, meaning that the HttpContextWrapper is returning null:

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.51Degrees.CloudDeviceDetection
   at Sitecore.FiftyOneDegrees.CloudDeviceDetection.System.Wrappers.HttpContextWrapper.get_Request() in C:\Users\j.dearsley.CLIENTSDEV\Desktop\Sitecore.51Degrees.CloudDeviceDetection-master\Sitecore.51Degrees.CloudDeviceDetection\System\Wrappers\HttpContextWrapper.cs:line 31
   at Sitecore.FiftyOneDegrees.CloudDeviceDetection.Rules.DeviceDetection.VisitorsDeviceType`1.Execute(T ruleContext) in C:\Users\p.fonseca.CLIENTSDEV\Desktop\Sitecore.51Degrees.CloudDeviceDetection-master\Sitecore.51Degrees.CloudDeviceDetection\Rules\DeviceDetection\VisitorsDeviceType.cs:line 15
   at Sitecore.Rules.Conditions.WhenCondition`1.Evaluate(T ruleContext, RuleStack stack)
   at Sitecore.Data.Items.DeviceItem.MatchesRules(HttpContextBase httpContext, SafeDictionary`2 customData)
   at Sitecore.Data.Items.DeviceItem.FindBestMatch(Database database, HttpContextBase httpContext)
   at Sitecore.Data.Items.DeviceItem.ResolveDevice(Database database, HttpContextBase httpContext)
   at Sitecore.Data.Items.ItemVisualization.ResolveContextDevice()
   at Sitecore.Data.Items.ItemVisualization.get_Layout()
   at Coveo.Framework.Items.ItemVisualizationWrapper.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Coveo.SearchProvider.Documents.DocumentBuilder.SetMetadata(IItem p_Item, CoveoIndexableItem p_CoveoIndexableItem)
   at Coveo.SearchProvider.Documents.DocumentBuilder.AddMetadata()
   at Coveo.SearchProvider.Documents.DocumentFactory.<>c__DisplayClass8.<CreateIndexableItem>b__7()
   at Coveo.SearchProvider.Documents.AbstractDocumentFactory.TryBuildDocument(Action p_Action, IIndexable p_Indexable)

Any help would be gratefully received.

Joe

**Comment by chowson** [comment]
Hi Joe,

Thanks for raising this, I understand the problem. When you say _When an item is crawled its calling the get_Layout method within Sitecore_, is the crawler is being run as a Sitecore Job?

If so, I think I need to make an update so that the rules that require the `HttpContext` handle the case where it is null and return _false_. If there's no context the rules can't work as the browser capabilities won't have been set.

Thanks

**Comment by jdearsley** [comment]
Hi Chris,

Yes, its run as a Sitecore Job, so yes that update sounds like the perfect fix. 

Would you have any idea how long such an update would take? trying to push our upgrade to 8.2 and having no items in our search index is a bit of a sticking point for us :-)

I could always fork the repo, but there are a fair number of places that this touches, and I don't want to make this take longer overall.

Thanks 

Joe

**Comment by chowson** [comment]
Hi Joe,

I've pushed a fix (1.4) and marked it as pre-release. If you want to download the updated Sitecore package, you can grab it from the [latest commit](https://github.com/chowson/Sitecore.51Degrees.CloudDeviceDetection/blob/master/SitecorePackages/Sitecore.51Degrees.CloudDeviceDetection.zip).

Only the DLL should differ from what you've got at the moment. You can see the changes in this [commit](https://github.com/chowson/Sitecore.51Degrees.CloudDeviceDetection/commit/da06dc5e2d98d1d498b10855328dd98795e7e2de). Could you give it a go and see if that resolves your issue? If you could then let me know the outcome then I will submit the updated package to the marketplace if all is good.

Thanks!

**Comment by jdearsley** [comment]
Hi Chris,

That's great, seems to have resolved the issue, Web index is now full again and no errors in the log.

Many thanks

Joe

**Comment by chowson** [comment]
Great, thanks for the feedback. I've now submitted the update to the marketplace.
